export const rentMock = [
  {
    carMark: "Ford",
    carModel: "Aerostar",
    carYear: 1993,
    rentPrice: 133,
    carImage:
      "https://www.edmunds.com/assets/m/ford/aerostar/1993/oem/1993_ford_aerostar_passenger-minivan_xl_fq_oem_1_500.jpg",
    rentHouse: "Moore and Sons",
    rentCity: "Mannheim",
    contact: "moore.sons@gmail.com",
  },
  {
    carMark: "Oldsmobile",
    carModel: "Ciera",
    carYear: 1993,
    rentPrice: 100,
    carImage:
      "https://www.scrapcatprices.com/wp-content/uploads/2020/09/1709062300.jpg",
    rentHouse: "Moore and Sons",
    rentCity: "Mannheim",
    contact: "moore.sons@gmail.com",
  },
  {
    carMark: "Ford",
    carModel: "F150",
    carYear: 2003,
    rentPrice: 75,
    carImage:
      "https://file.kelleybluebookimages.com/kbb/base/house/2003/2003-Ford-F150%20Regular%20Cab-FrontSide_FT15R001_505x375.jpg",
    rentHouse: "Moore and Sons",
    rentCity: "Mannheim",
    contact: "moore.sons@gmail.com",
  },
  {
    carMark: "Porsche",
    carModel: "911",
    carYear: 2004,
    rentPrice: 107,
    carImage:
      "https://www.tradeclassics.com/wp-content/uploads/2022/08/2004-porsche-911-black-main-hero.jpg",
    rentHouse: "Moore and Sons",
    rentCity: "Mannheim",
    contact: "moore.sons@gmail.com",
  },
  {
    carMark: "Chrysler",
    carModel: "Sebring",
    carYear: 2004,
    rentPrice: 192,
    carImage:
      "https://www.motortrend.com/uploads/sites/5/2004/05/112_0406_2004_Chrysler_Sebring_03z-2004_Chrysler_Sebring-Rear_Drivers_Side_View.jpg",
    rentHouse: "Haley-Mayer",
    rentCity: "Rotterdam",
    contact: "haley.mayer@gmail.com",
  },
  {
    carMark: "Buick",
    carModel: "LaCrosse",
    carYear: 2007,
    rentPrice: 142,
    carImage:
      "https://media.ed.edmunds-media.com/buick/lacrosse/2007/oem/2007_buick_lacrosse_sedan_cxs_fq_oem_4_1600.jpg",
    rentHouse: "Haley-Mayer",
    rentCity: "Rotterdam",
    contact: "haley.mayer@gmail.com",
  },
  {
    carMark: "Lincoln",
    carModel: "Town Car",
    carYear: 2009,
    rentPrice: 104,
    carImage:
      "https://bringatrailer.com/wp-content/uploads/2023/04/2009_lincoln_town-car_img_9367-48414.jpg",
    rentHouse: "Haley-Mayer",
    rentCity: "Rotterdam",
    contact: "haley.mayer@gmail.com",
  },
  {
    carMark: "Nissan",
    carModel: "Altima",
    carYear: 1993,
    rentPrice: 85,
    carImage:
      "https://www.edmunds.com/assets/m/nissan/altima/1993/oem/1993_nissan_altima_sedan_gle_fq_oem_1_500.jpg",
    rentHouse: "Haley-Mayer",
    rentCity: "Rotterdam",
    contact: "haley.mayer@gmail.com",
  },
  {
    carMark: "Lotus",
    carModel: "Esprit",
    carYear: 1991,
    rentPrice: 84,
    carImage:
      "https://bringatrailer.com/wp-content/uploads/2020/08/1991_lotus_esprit_160192359066ec4fa56eb1e1991_lotus_esprit_160145533895d565ef66e7db5371550-b50e-4315-8934-def2941ce826-34FxuZ.jpg?fit=1906%2C1270",
    rentHouse: "Schneider LLC",
    rentCity: "Maribor",
    contact: "schneider@yahoo.com",
  },
  {
    carMark: "Chevrolet",
    carModel: "Express",
    carYear: 2010,
    rentPrice: 140,
    carImage:
      "https://static0.carbuzzimages.com/wordpress/wp-content/uploads/2024/03/340214-14.jpg",
    rentHouse: "Schneider LLC",
    rentCity: "Maribor",
    contact: "schneider@yahoo.com",
  },
  {
    carMark: "Mercedes-Benz",
    carModel: "Sprinter 3500",
    carYear: 2011,
    rentPrice: 121,
    carImage:
      "https://vehicle-images.dealerinspire.com/6031-110009882/W1Y8ND3Y7RT175253/5326b026a77ddd7d912c00cee7db72ac.jpg",
    rentHouse: "Schneider LLC",
    rentCity: "Maribor",
    contact: "schneider@yahoo.com",
  },
  {
    carMark: "Audi",
    carModel: "A6",
    carYear: 1998,
    rentPrice: 152,
    carImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdYjZGCi2mT6xWt3KWSli-617sYlmf2hXyOQ&usqp=CAU",
    rentHouse: "Schneider LLC",
    rentCity: "Maribor",
    contact: "schneider@yahoo.com",
  },
  {
    carMark: "Mazda",
    carModel: "MX-5",
    carYear: 1998,
    rentPrice: 123,
    carImage:
      "https://www.tradeclassics.com/wp-content/uploads/2022/07/1998-Mazda-MX5-SparkleGreen-Main-Hero-scaled.jpg",
    rentHouse: "Legros-Treutel",
    rentCity: "Graz",
    contact: "legros.treutel@gmail.com",
  },
  {
    carMark: "Lincoln",
    carModel: "Navigator L",
    carYear: 2008,
    rentPrice: 138,
    carImage:
      "https://bringatrailer.com/wp-content/uploads/2024/02/2008_lincoln_navigator_a8483042-43510.jpg?fit=940%2C627",
    rentHouse: "Legros-Treutel",
    rentCity: "Graz",
    contact: "legros.treutel@gmail.com",
  },
  {
    carMark: "Bugatti",
    carModel: "Veyron",
    carYear: 2011,
    rentPrice: 350,
    carImage:
      "https://www.tomhartleyjnr.com/wp-content/uploads/2019/05/795002-003_1024x768.jpg",
    rentHouse: "Legros-Treutel",
    rentCity: "Graz",
    contact: "legros.treutel@gmail.com",
  },
  {
    carMark: "Honda",
    carModel: "Ridgeline",
    carYear: 2007,
    rentPrice: 132,
    carImage:
      "https://file.kelleybluebookimages.com/kbb/base/house/2007/2007-Honda-Ridgeline-FrontSide_HTRDRTL071_505x375.jpg",
    rentHouse: "Legros-Treutel",
    rentCity: "Graz",
    contact: "legros.treutel@gmail.com",
  },
  {
    carMark: "Lincoln",
    carModel: "Navigator",
    carYear: 2004,
    rentPrice: 176,
    carImage:
      "https://i.pinimg.com/736x/c7/a2/56/c7a25679da3685b84f4ffbfa1bb8a076.jpg",
    rentHouse: "Lockman-Corkery",
    rentCity: "Frankfurt",
    contact: "lockman.c@outlook.com",
  },
  {
    carMark: "Lexus",
    carModel: "LX",
    carYear: 2000,
    rentPrice: 76,
    carImage: "https://i.redd.it/5tf9z29l52e81.jpg",
    rentHouse: "Lockman-Corkery",
    rentCity: "Frankfurt",
    contact: "lockman.c@outlook.com",
  },
  {
    carMark: "Volkswagen",
    carModel: "Jetta",
    carYear: 1996,
    rentPrice: 113,
    carImage:
      "https://media.ed.edmunds-media.com/volkswagen/jetta/1996/oem/1996_volkswagen_jetta_sedan_glx-vr6_fq_oem_1_500.jpg",
    rentHouse: "Lockman-Corkery",
    rentCity: "Frankfurt",
    contact: "lockman.c@outlook.com",
  },
  {
    carMark: "Dodge",
    carModel: "Ram",
    carYear: 1994,
    rentPrice: 193,
    carImage:
      "https://journal.classiccars.com/media/2023/07/39882714-1994-dodge-1500-std.jpg",
    rentHouse: "Lockman-Corkery",
    rentCity: "Frankfurt",
    contact: "lockman.c@outlook.com",
  },
];
